# This a test docker-compose file, that can be used to run test locally with any app/site docker image
# ${SITE_IMAGE}, ${SITE_URL:-http://site-dev:3000} & ${SUITE_NAME}

version: "3"

services:
  site:
    image: ${SITE_IMAGE}
    #d442cdb4f03e
    container_name: site-dev
    #shm_size: 2gb
    environment:
      - NEXT_PUBLIC_CONFIG_URL=http://api.pro/
    ports:
      - "3000:3000"

  testcode:
    build: .
    image: wdio-test
    container_name: wdio-test
    #shm_size: 2gb
    depends_on:
      - formhouse
      - chrome
      - firefox
      - edge
    links:
      - selenium-hub
    environment:
      - GUI=false
      - DOCKER_SERVICE=true
      - SITE_URL=${FORMHOUSE_SITE_URL:-http://site-dev:3000}
      - SUITE_NAME=${SUITE_NAME}
      - USER_EMAIL_ID=wdio@test.com
      - PASSWORD=wdiouser
    volumes:
      - /wdio-test/allure-results:/app/allure-results

  chrome:
    image: selenium/node-chrome:4.7.1-20221208
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  firefox:
    image: selenium/node-firefox:4.7.2-20221217
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.7.2-20221217
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.7.1-20221208
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
